stages:
- test
#- build
#- deploy

# include:
#   - template: Code-Quality.gitlab-ci.yml

# code_quality:
#   tags:
#   - quality

# code_quality_html:
#   extends: code_quality
#   variables:
#     REPORT_FORMAT: html
#   artifacts:
#     paths: [gl-code-quality-report.html]