"""Add Index on device bearer

Revision ID: 9267f20ab137
Revises: 6439e23d8a79
Create Date: 2023-01-15 16:55:49.332997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9267f20ab137'
down_revision = '6439e23d8a79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_gps_tracker_tracker_bearer'), 'gps_tracker', ['tracker_bearer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gps_tracker_tracker_bearer'), table_name='gps_tracker')
    # ### end Alembic commands ###
