"""Add column - tracker url id

Revision ID: 9d02f2cdd82f
Revises: b4361c11c891
Create Date: 2022-11-19 21:13:10.229176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d02f2cdd82f'
down_revision = 'b4361c11c891'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gps_tracker', sa.Column('url_id', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_gps_tracker_url_id'), 'gps_tracker', ['url_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gps_tracker_url_id'), table_name='gps_tracker')
    op.drop_column('gps_tracker', 'url_id')
    # ### end Alembic commands ###
