"""Add Indexes

Revision ID: b4361c11c891
Revises: 7bb1b21c40e7
Create Date: 2022-11-19 20:49:17.922453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4361c11c891'
down_revision = '7bb1b21c40e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('per_app', 'gps_record', ['device', 'app'], unique=False)
    op.create_index('unique_tracker', 'gps_tracker', ['device', 'app', 'tracker_bearer'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_tracker', table_name='gps_tracker')
    op.drop_index('per_app', table_name='gps_record')
    # ### end Alembic commands ###
