"""Add column - active

Revision ID: ca540e51e657
Revises: 9267f20ab137
Create Date: 2023-01-15 16:59:28.676101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca540e51e657'
down_revision = '9267f20ab137'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gps_tracker', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gps_tracker', 'active')
    # ### end Alembic commands ###
